apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: S3-Bucket
  title: Create S3-Bucket
  description: S3-Bucket Creation
  tags: ['recommended']
spec:
  owner: guests
  type: service
  parameters:
    - title: S3 Bucket Creation
      required:
         - BucketName
         - BucketType  
      properties:
        BucketName:
          title: Bucket Name.
          type: string
          description: Name of the Bucket to be created.
          ui:autofocus: true
          ui:options:
            rows: 5

        BucketType:
          title: Type of Bucket.
          type: string
          description: Type of the bucket that you want to create, for eg:- private, public.
          enum:
            - private
            - public
        action:
          title: action
          type: string
          description: What action do you want to perform? Create or delete?
          enum:
            - apply
            - destroy

    - title: Choose a Repository Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Location of the repository
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
# Getting the all the files/details from the template
    - id: fetch-base
      name: Fetching Details from content folder
      action: fetch:template
      input:
        url: ./content  # Location of the content directory where catlog-info.yaml file is present for the template
        values:
          name: ${{ parameters.BucketName}}

# Publish the content of the current working directory to our github directory
    - id: publish
      name: Publishing Details
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This repo is to create a s3 bucket ${{ parameters.BucketName }} using backstage.
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public # or 'internal' or 'private'
        # defaultBranch: master

# Triggering CI-CD to create resource in our case github action. 
    - id: github-action
      name: Starting GitHub action
      action: github:actions:dispatch
      input:
        workflowId:  s3bucket.yaml # ID of GitHub action WorkFlow
        repoUrl: 'github.com?repo=s3-catalog&owner=gangabadiger'
        branchOrTagName: 'master'
        workflowInputs:
          bukcetName: ${{ parameters.BucketName }}
          bucketType: ${{ parameters.BucketType }}
          action: ${{ parameters.action }}

# Registering new component in the catalog of backstage.
    - id: register
      name: Registering the new Component 
      action: catalog:register
      input:
        repoContentsUrl: ${{steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml' # where the info of the catalog is stored.

# Output links  are displayed to the user after the template execution.
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
