---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: codemonk14
  email: nikhil.linga143@gmail.com
spec:
  memberOf: [guests]
---

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gangabadiger
  email: gangabadiger7@gmail.com
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
