apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: s3 catalog
  annotations:
    github.com/project-slug: gangabadiger/s3-catalog # Change the value to your github repo which contains terraform code.
    backstage.io/techdocs-ref: dir:.
  title: 'S3 Bucket Creation Catalog' # you can give any title
  description: S3 Bucket Creation Catalog for testing. # Change Description accordingly
spec:
  type: service
  owner: user:guest
  lifecycle: experimental