# Define the name of the GitHub Action workflow
name: Create a s3 bucket
# This workflow is manually triggered using the GitHub Actions UI
on:
  workflow_dispatch:
    # Define inputs that are required for the manual trigger
    inputs:
      bucketName:
        description: 'Name of the S3 Bucket'  # What's this input for?
        required: true  # Is it optional or required?
      bucketType:
        description: 'S3 Bucket type'
        required: true
      action:
        description: 'Action to perform (apply/destroy)'
        required: true
# Jobs to be executed in this workflow
jobs:
  # Job for applying the s3 bucket
  apply_s3:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest
    
    # Execute this step only if the action input is "apply"
    if: ${{ github.event.inputs.action == 'apply' }}
    # Define the steps for this job
    steps:
    
    # checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

# adding aws keys. Please store the value of these key in GitHub variables
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
    
    # Initialize Terraform 
    - name: Terraform Init
      run: terraform init
      working-directory: .  # Where should this command be run?
      
    # Format Terraform code
    - name: Terraform Format
      run: terraform fmt
      working-directory: .
      
    # Validate the Terraform code 
    - name: Terraform Validate
      run: terraform validate
      working-directory: .
      
    # Apply the Terraform plan
    - name: Terraform vars
    - name: terraform apply
      run: terraform apply -var bucketName=${{ github.event.inputs.bucketName }} -var bucketType=${{ github.event.inputs.bucketType }} -auto-approve
      working-directory: .

  # Destroying the  s3 bucket
  destroy_s3:
    runs-on: ubuntu-latest
    
    # Execute this job only if the action input is "destroy"
    if: ${{ github.event.inputs.action == 'destroy' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
# adding aws keys. Please store the value of these key in GitHub variables
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        
    - name: Terraform Init
      run: terraform init
      working-directory: .
      
    - name: Terraform FMT
      run: terraform fmt
      working-directory: .
      
      
    # Destroy all resources 
    - name: Terraform Destroy
    - name: terraform apply
      run: terraform destroy -var bucketName=${{ github.event.inputs.bucketName }} -auto-approve
      working-directory: .
